In [2]:
import pandas as pd
import numpy as np

In [3]:
# Question 1

pd.__version__

'2.0.3'

In [4]:
# Question 2

housing_csv = pd.read_csv('housing.csv')
len(housing_csv.columns)

10

In [9]:
# Question 3

print("which columns have null?")
print(housing_csv.isnull().any())

print("which columns have na?")
print(housing_csv.isna().any())

which columns have null?
longitude             False
latitude              False
housing_median_age    False
total_rooms           False
total_bedrooms         True
population            False
households            False
median_income         False
median_house_value    False
ocean_proximity       False
dtype: bool
which columns have na?
longitude             False
latitude              False
housing_median_age    False
total_rooms           False
total_bedrooms         True
population            False
households            False
median_income         False
median_house_value    False
ocean_proximity       False
dtype: bool


In [13]:
# Question 4

print(housing_csv["ocean_proximity"].unique())
print(len(housing_csv["ocean_proximity"].unique()))

['NEAR BAY' '<1H OCEAN' 'INLAND' 'NEAR OCEAN' 'ISLAND']
5


In [24]:
# Question 5

housing_csv[housing_csv["ocean_proximity"] == "NEAR BAY"]["median_house_value"].mean()

259212.31179039303

In [35]:
# Question 6

print("before fillna")
print(housing_csv["total_bedrooms"].mean())
print("after fillna using the average total bedrooms")
print(housing_csv["total_bedrooms"].fillna(537.871).mean())

before fillna
537.8705525375618
after fillna
537.8705570251938


In [5]:
# Question 7

sel = housing_csv[housing_csv["ocean_proximity"] == "ISLAND"][["housing_median_age", "total_rooms", "total_bedrooms"]]
X = sel.to_numpy()
print(X)
print(X.T)
XTX = np.dot(X.T, X)
print(XTX)
XTX_inv = np.linalg.inv(XTX)
print(XTX_inv)
y = [950, 1300, 800, 1000, 1300]
w = np.dot(np.dot(XTX_inv, X.T), y)
print(w)

[[  27. 1675.  521.]
 [  52. 2359.  591.]
 [  52. 2127.  512.]
 [  52.  996.  264.]
 [  29.  716.  214.]]
[[  27.   52.   52.   52.   29.]
 [1675. 2359. 2127.  996.  716.]
 [ 521.  591.  512.  264.  214.]]
[[9.6820000e+03 3.5105300e+05 9.1357000e+04]
 [3.5105300e+05 1.4399307e+07 3.7720360e+06]
 [9.1357000e+04 3.7720360e+06 9.9835800e+05]]
[[ 9.19403586e-04 -3.66412216e-05  5.43072261e-05]
 [-3.66412216e-05  8.23303633e-06 -2.77534485e-05]
 [ 5.43072261e-05 -2.77534485e-05  1.00891325e-04]]
[23.12330961 -1.48124183  5.69922946]
